@startuml p03-thermostat
scale 2
!include _common.iuml
hide circle
hide empty members

class Thermostat {
  - temperature : double
  --
  + Thermostat()
  + setTemperature(temperature : double) : void
  + getTemperature() : double
}
@enduml
