@startuml p10-tugas-auditlog
scale 2
!include _common.iuml
hide circle
hide empty members
left to right direction

class Bank {
  + printAuditLog() : void
}

interface Auditable {
  + auditLog() : String
}

Bank ..> Auditable : instanceof
@enduml
