@startuml p10-invalidtemperature-exception
scale 2
!include _common.iuml
hide circle
hide empty members
left to right direction

class Exception {
}

class InvalidTemperatureException {
}

class Thermostat {
  - temperature : int
  --
  + setTemperature(value : int) : void
}

Exception <|-- InvalidTemperatureException
Thermostat ..> InvalidTemperatureException : throws
@enduml
