@startuml p15-tugas-bankminiframe-constructor
scale 2
!include _common.iuml
hide circle
hide empty members
left to right direction

class BankMiniFrame {
  + BankMiniFrame(username : String)
}
@enduml
